/// <reference types="cypress" />
require("cypress-xpath");
const { Steps } = require("../Steps");
const { Home } = require("../pages_object/Home");
const { CreateReport } = require("../Utilities/createReport");
let steps = new Steps();
let home = new Home();
let createReport = new CreateReport(0);
let folderBefore = "changuePasswordBefore";
let folderAfter = "changuePasswordAfter";
 
describe("Change Password", () => {
  it("Como usuario deseo modificar mi contraseña de perfil", () => {
    steps.setIdScreenImage("a");
    steps.setDirrectoryReport(folderAfter);
    steps.setURLGhost(home.URLGhost);
    steps.login();
    steps.TakePicture();
    steps.I_click_perfil();
    steps.waiting(1000);
    steps.TakePicture();
    steps.I_click_your_profile();
    steps.waiting(1000);
    steps.TakePicture();
    steps.I_enter_old_password();
    steps.I_enter_new_password();
    steps.I_enter_verify_password();
    steps.I_click_change_password();
    steps.waiting(1000);
    steps.I_click_save_your_profile();
    steps.TakePicture();
    steps.waiting(10000);
    steps.waiting(3000);
    steps.I_click_perfil();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_close_my_session();
    steps.waiting(3000);
    steps.TakePicture();
    steps.I_enter_email_sign_in();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_enter_new_password_sign_in();
    steps.I_click_next();
    steps.waiting(3000);
    steps.TakePicture();
    steps.I_click_perfil();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_click_your_profile();
    steps.waiting(1500);
    steps.TakePicture();
    steps.I_enter_old_password_return();
    steps.I_enter_new_password_return();
    steps.I_enter_verify_password_return();
    steps.TakePicture();
    steps.I_click_change_password();
    steps.TakePicture();
    steps.waiting(10000);
    steps.TakePicture();
    steps.I_click_perfil();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_close_my_session();
    steps.waiting(2000);
    steps.TakePicture();
  });
  it("Como usuario deseo modificar mi contraseña de perfil version antigua", () => {
    steps.setIdScreenImage("a");
    steps.setDirrectoryReport(folderBefore);
    steps.setURLGhost(home.URLGhostOld);
    steps.login();
    steps.TakePicture();
    steps.I_click_perfilOld();
    steps.waiting(1000);
    steps.TakePicture();
    steps.I_click_your_profileOld();
    steps.waiting(1000);
    steps.TakePicture();
    steps.I_enter_old_password();
    steps.I_enter_new_password();
    steps.I_enter_verify_password();
    steps.I_click_change_password();
    steps.waiting(1000);
    steps.I_click_save_your_profileOld();
    steps.TakePicture();
    steps.waiting(10000);
    steps.waiting(3000);
    steps.I_click_perfil();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_close_my_session();
    steps.waiting(3000);
    steps.TakePicture();
    steps.I_enter_email_sign_in();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_enter_new_password_sign_in();
    steps.I_click_next();
    steps.waiting(3000);
    steps.TakePicture();
    steps.I_click_perfil();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_click_your_profile();
    steps.waiting(1500);
    steps.TakePicture();
    steps.I_enter_old_password_return();
    steps.I_enter_new_password_return();
    steps.I_enter_verify_password_return();
    steps.TakePicture();
    steps.I_click_change_password();
    steps.TakePicture();
    steps.waiting(10000);
    steps.TakePicture();
    steps.I_click_perfil();
    steps.waiting(2000);
    steps.TakePicture();
    steps.I_close_my_session();
    steps.waiting(2000);
    steps.TakePicture();
  });

  it("Construir reporte", () => {
    let moduleTest = "Change password";
    createReport.executeTest(15, folderAfter, folderBefore, moduleTest);
    cy.task("createMyReport", "\\cypress\\screenshots\\report1.html").then(
      (p) => {
        alert(`The reports for ${moduleTest} is in ${p} `);
      }
    );
  });
});
